// @vitest-environment jsdom
import { expect, test, vi } from 'vitest';
test('activation, source change, missing EXIF and shutdown', async () => {
  let enabled = false;
  const listeners: ((changes: object, area: string) => void)[] = [];
  let intersect: IntersectionObserverCallback;
  vi.stubGlobal('IntersectionObserver', class {
    constructor(callback: IntersectionObserverCallback) { intersect = callback; }
    observe() {} unobserve() {} disconnect() {}
  });
  const sendMessage = vi.fn().mockResolvedValue({status:'ok',data:{focal:35,iso:160,exposure:1/60,aperture:1.8,flash:15,camera:'NIKON Z 6',lens:'NIKKOR Z 35mm f/1.8 S'}});
  let summaryListener: (message: unknown, sender: object, respond: (summary: unknown) => void) => void;
  const shadows: ShadowRoot[] = [];
  const attach = HTMLElement.prototype.attachShadow;
  vi.spyOn(HTMLElement.prototype, 'attachShadow').mockImplementation(function(init) { const root = attach.call(this, init); shadows.push(root); return root; });
  vi.stubGlobal('chrome', {storage:{local:{get:async()=>({enabled})},onChanged:{addListener:(fn:typeof listeners[number])=>listeners.push(fn)}},runtime:{id:'test-extension',sendMessage,onMessage:{addListener:(fn:typeof summaryListener)=>{summaryListener=fn;}}}});
  vi.stubGlobal('requestAnimationFrame', (fn: FrameRequestCallback) => setTimeout(fn, 0));
  document.body.innerHTML = '<ul><li data-id="1"><img src="https://images.pixieset.com/123/test-medium.jpg"></li></ul>';
  const image = document.querySelector('img')!;
  Object.defineProperty(image, 'getBoundingClientRect', {value:()=>({left:0,top:0,bottom:240,right:360,width:360,height:240})});
  Object.defineProperty(image, 'getClientRects', {value:()=>[{}]});
  await import('../src/content'); await new Promise(resolve => setTimeout(resolve, 10));
  expect(document.querySelector('pixieset-exif-label')).toBeNull();
  enabled = true; listeners[0]({enabled:{newValue:true}},'local');
  intersect!([{target:image,isIntersecting:true}] as IntersectionObserverEntry[], {} as IntersectionObserver);
  await new Promise(resolve=>setTimeout(resolve,10));
  expect(sendMessage).toHaveBeenCalledTimes(1);
  const panelHost = document.querySelector<HTMLElement>('pixieset-exif-panel')!;
  expect(panelHost.style.display).toBe('block');
  const panelReply = vi.fn();
  summaryListener!({type:'panel'},{id:'test-extension'},panelReply);
  expect(panelHost.style.display).toBe('none');
  summaryListener!({type:'panel'},{id:'test-extension'},panelReply);
  expect(panelReply).toHaveBeenLastCalledWith({visible:true,enabled:true});
  expect(panelHost.style.display).toBe('block');
  expect(document.querySelector('pixieset-exif-label')).not.toBeNull();
  expect(shadows.at(-1)!.querySelector('.lens')!.textContent).toBe('NIKKOR Z 35mm f/1.8 S');
  const reply = vi.fn();
  summaryListener!({type:'summary'},{id:'test-extension'},reply);
  expect(reply.mock.calls.at(-1)![0]).toMatchObject({checked:1,available:1,flash:{known:1,fired:1}});
  listeners[0]({display:{newValue:{fontSize:16,opacity:50,fields:{lens:false,iso:false}}}},'local');
  expect(shadows.at(-1)!.querySelector('.lens')!.textContent).toBe('');
  expect(shadows.at(-1)!.textContent).not.toContain('ISO 160');
  expect(shadows.at(-1)!.querySelector<HTMLElement>('.label')!.style.fontSize).toBe('16px');
  expect(sendMessage).toHaveBeenCalledTimes(1);

  listeners[0]({display:{newValue:{mode:'hover'}}},'local');
  expect(document.querySelector<HTMLElement>('pixieset-exif-label')!.style.display).toBe('none');
  document.dispatchEvent(new MouseEvent('pointermove',{clientX:20,clientY:50}));
  expect(document.querySelector<HTMLElement>('pixieset-exif-label')!.style.display).toBe('block');
  document.dispatchEvent(new MouseEvent('pointerout',{relatedTarget:null}));
  expect(document.querySelector<HTMLElement>('pixieset-exif-label')!.style.display).toBe('none');
  image.src = 'https://images.pixieset.com/123/test-xxlarge.jpg';
  await new Promise(resolve=>setTimeout(resolve,10));
  intersect!([{target:image,isIntersecting:true}] as IntersectionObserverEntry[], {} as IntersectionObserver);
  await new Promise(resolve=>setTimeout(resolve,10));
  expect(sendMessage).toHaveBeenCalledTimes(1);
  summaryListener!({type:'summary'},{id:'test-extension'},reply);
  expect(reply.mock.calls.at(-1)![0]).toMatchObject({checked:1,available:1});
  image.src = 'https://images.pixieset.com/123/second-medium.jpg';
  await new Promise(resolve=>setTimeout(resolve,10));
  sendMessage.mockResolvedValueOnce({status:'missing'});
  intersect!([{target:image,isIntersecting:true}] as IntersectionObserverEntry[], {} as IntersectionObserver);
  await new Promise(resolve=>setTimeout(resolve,10));
  expect(sendMessage).toHaveBeenLastCalledWith({type:'read',url:image.src});
  summaryListener!({type:'summary'},{id:'test-extension'},reply);
  expect(reply.mock.calls.at(-1)![0]).toMatchObject({checked:2,available:1,missing:1});
  listeners[0]({enabled:{newValue:false}},'local');
  expect(document.querySelector('pixieset-exif-label')).toBeNull();
  summaryListener!({type:'summary'},{id:'test-extension'},reply);
  expect(reply.mock.calls.at(-1)![0]).toMatchObject({checked:2});
  window.history.pushState({}, '', '/another-gallery/');
  summaryListener!({type:'summary'},{id:'test-extension'},reply);
  expect(reply.mock.calls.at(-1)![0]).toMatchObject({checked:0});
  // Reload invalidates APIs synchronously; it must not produce an unhandled rejection.
  image.src = 'https://images.pixieset.com/123/third-medium.jpg';
  listeners[0]({enabled:{newValue:true}},'local');
  sendMessage.mockImplementationOnce(() => { throw new Error('Extension context invalidated.'); });
  intersect!([{target:image,isIntersecting:true}] as IntersectionObserverEntry[], {} as IntersectionObserver);
  await new Promise(resolve=>setTimeout(resolve,10));
  expect(document.querySelector('pixieset-exif-label')).toBeNull();
  expect(document.querySelector('pixieset-exif-panel')).toBeNull();
  const calls = sendMessage.mock.calls.length;
  document.dispatchEvent(new Event('scroll'));
  await new Promise(resolve=>setTimeout(resolve,10));
  expect(sendMessage).toHaveBeenCalledTimes(calls);
  vi.restoreAllMocks();
  vi.unstubAllGlobals();
});

test('whole section scan updates the same summary, caches results and resets on navigation', async () => {
  vi.resetModules();
  const listeners: ((changes: object, area: string) => void)[] = [];
  const location = new URL('https://demo.pixieset.com/demo/party/');
  vi.stubGlobal('location', location);
  vi.stubGlobal('IntersectionObserver', class { observe() {} unobserve() {} disconnect() {} });
  vi.stubGlobal('requestAnimationFrame', (fn: FrameRequestCallback) => setTimeout(fn, 0));
  const urls = [1, 2, 3].map(n=>`https://images.pixieset.com/1/photo${n}-medium.jpg`);
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue({ok:true,json:async()=>({status:'success',content:JSON.stringify(urls.map((pathMedium,id)=>({id,pathMedium}))),isLastPage:true})}));
  let active = 0, max = 0;
  const read = vi.fn(async ({url}:{url:string}) => { active++; max=Math.max(max,active); await new Promise(resolve=>setTimeout(resolve,5));active--;return url===urls[2]?{status:'missing'}:{status:'ok',data:{focal:url===urls[0]?35:85}}; });
  let message!: (input: object, sender: object, reply: (data: unknown)=>void)=>void;
  vi.stubGlobal('chrome',{storage:{local:{get:async()=>({enabled:true})},onChanged:{addListener:(fn:typeof listeners[number])=>listeners.push(fn)}},runtime:{id:'test',sendMessage:read,onMessage:{addListener:(fn:typeof message)=>{message=fn;}}}});
  document.body.innerHTML = `<script type="application/json">PixiesetClient.init({'collectionId':123,'collectionUrlKey':'demo','favKey':null});</script>`;
  await import('../src/content'); await new Promise(resolve=>setTimeout(resolve,10));
  const reply = vi.fn(); message({type:'section'},{id:'test'},reply);
  await new Promise(resolve=>setTimeout(resolve,40));
  message({type:'summary'},{id:'test'},reply);
  expect(reply.mock.calls.at(-1)![0]).toMatchObject({checked:3,available:2,missing:1,section:{status:'done',processed:3,total:3},focals:[{name:'35 mm',count:1},{name:'85 mm',count:1}]});
  expect(max).toBe(2);
  message({type:'section'},{id:'test'},reply); await new Promise(resolve=>setTimeout(resolve,20));
  expect(read).toHaveBeenCalledTimes(3);
  location.pathname='/demo/other/'; message({type:'summary'},{id:'test'},reply);
  expect(reply.mock.calls.at(-1)![0]).toMatchObject({checked:0,section:{status:'idle'}});
  listeners[0]({enabled:{newValue:false}},'local');
  vi.unstubAllGlobals();
});
